server:
  port: 0
  servlet:
    encoding:
      force-response: true
spring:
  application:
    name: order-service
  jpa:
    show_sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL57Dialect
      ddl-auto: create
    generate-ddl: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
  h2:
    console:
      enabled: true
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
